### ISSUE TITLE
Action fails

### ISSUE THREAD

**Issue by nikolat** [Taromati2/ukagaka-mirror-md5-CI-build#1]
The action failed in the following repository.
https://github.com/nikolat/ukagaka-simultaneous-interpreter/actions/runs/2937495188

Other repositories succeeded despite the same definition.
Does it fail if the repository name is too long?

**Comment by steve02081504** [comment]
> https://github.com/ukatech/ukagaka-mirror-md5-CI-build/issues/1#issue-1352895502

Sorry to see the message so late, but could you try running CI again?
I've just tested it and it seems to be working fine
https://github.com/steve02081504/ukagaka-simultaneous-interpreter/commit/9c7abf67191d27d9465025ba389f9e0db9c72719

**Comment by nikolat** [comment]
Thanks for your response.
But the action failed again.
https://github.com/nikolat/ukagaka-simultaneous-interpreter/actions/runs/3360057856/jobs/5568789921

I also tried it myself by copying it to another repository, and the action was successful.
I have no idea what caused it....

**Comment by steve02081504** [comment]
> https://github.com/ukatech/ukagaka-mirror-md5-CI-build/issues/1#issuecomment-1296823532

Although I don't know why, I think it's a problem with the token permissions
Let's try creating a token with write permissions to try to fix this!
1. https://github.com/settings/personal-access-tokens/new
2. https://docs.github.com/ja/actions/security-guides/encrypted-secrets
3. Adding a token parameter to action like `token: ${{ secrets.MY_TOKEN }}`

**Comment by steve02081504** [comment]
Once you have determined that this is a token issue, there are two methods you can use to resolve it.
1. delete the entire repo and get an new one then re-upload the file to avoid maintaining and using the token
This will throw out all the repo's statistics (such as star and  project settings) and version releases, but may solve the problem completely
2. keep the token in use and update it from time to time to avoid brute force cracking

**Comment by nikolat** [comment]
It does not seem to work.
https://github.com/nikolat/ukagaka-simultaneous-interpreter/actions/runs/3360291283/jobs/5569299820

The same error seemed to occur with actions-go/push.
https://github.com/actions-go/push/issues/3

It doesn't seem to be something we can fix.
Thank you for your efforts.
The impact is limited, so you may close this issue.

**Comment by steve02081504** [comment]
> https://github.com/ukatech/ukagaka-mirror-md5-CI-build/issues/1#issuecomment-1296873684

I guess we could try deleting the whole repo and opening a repo with the same name and re-uploading the file if you want😥

**Comment by nikolat** [comment]
It worked fine.
Thank you.
https://github.com/nikolat/ukagaka-simultaneous-interpreter/commit/f6a254adf26d24f4c2d093bcc3ab9d1d5adaa2d5

**Comment by steve02081504** [comment]
Glad to see this fix is working! 😂

**Comment by steve02081504** [comment]
Don't forget to fix your repo's description, topics and release!
Hopefully people won't encounter 404's nar download links🙏
